import React, { FC } from 'react';
import Head from 'next/head';

import PopularOffers from 'components/PopularOffers/PopularOffers';
import MainHero from 'components/HomePage/MainHero/MainHero';
import PopularCategories from 'components/HomePage/PopularCategories/PopularCategories';
import PromoteBlock from 'components/HomePage/PromoteBlock/PromoteBlock';
import Footer from 'components/Footer/Footer';

import styles from 'styles/pages/Home.module.css';
import { API_URL } from 'services/api/base';
import { Category, Master } from '_types';

interface Props {
  categories: Category[];
  popularMasters: Master[];
}

const Home: FC<Props> = ({ categories, popularMasters }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MainHero />
        <div className="container">
          <PopularOffers
            title="Popular offers"
            popularMasters={popularMasters}
          />
          <PopularCategories categories={categories} />
          <PromoteBlock />
          <PromoteBlock isReverse />
        </div>
      </main>

      <Footer />
    </div>
  );
};

export const getServerSideProps = async () => {
  const categoriesJson = await fetch(`${API_URL}/categories`);
  const categories = await categoriesJson.json();

  const popularMastersJson = await fetch(`${API_URL}/users/popular`);
  const popularMasters = await popularMastersJson.json();
  return {
    props: { categories, popularMasters },
  };
};

export default Home;
